project:
  type: website

website:
  title: "ROAM"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - resources.qmd
      - feature_data.qmd
      - icon: github
        href: https://github.com/ROAM-JCU
format:
  html:
    theme: litera
    css: styles.css
    toc: true
